local f = io.open('KASPER.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 KASPER.sh')
os.execute('killall -9 tg')
os.execute('rm -rf KASPER.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('KASPER.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 KASPER.sh')
os.execute('screen ./KASPER.sh')
